# Generated by Django 5.0.6 on 2024-05-28 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_visit', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('user_role', models.CharField(choices=[('заказчик', 'Заказчик'), ('Зооняня', 'Зооняня')], default='заказчик', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('user_type', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
