# Generated by Django 5.0.6 on 2024-06-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_bio_alter_customer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('заказчик', 'Я - клиент'), ('исполнитель', 'Я - ситтер')], default='заказчик', max_length=20),
        ),
    ]
