# Generated by Django 5.0.6 on 2024-06-08 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='customer',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Показывать Email?'),
        ),
        migrations.AddField(
            model_name='customer',
            name='show_phone',
            field=models.BooleanField(default=False, verbose_name='Показывать телефон?'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='images/profile/user_default.png', null=True, upload_to='images/profile/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('собака', 'Собака'), ('кошка', 'Кошка')], default='собака', max_length=6)),
                ('image', models.ImageField(blank=True, default='images/profile/pet_default.png', null=True, upload_to='images/pets/%Y/%m/%d/')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.CharField(choices=[('1', '1-5 кг'), ('2', '6-10 кг'), ('3', '11-20 кг'), ('4', '21+ кг')], default='1', max_length=10)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
