# Generated by Django 5.0.6 on 2024-05-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_phone',
            new_name='phone',
        ),
    ]
