# Generated by Django 5.0.6 on 2024-06-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pet_age_months_pet_age_years_pet_breed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='host',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст, месяцев'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст, лет'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, default='images/profile/pet_default.png', null=True, upload_to='images/pets/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.CharField(choices=[('1', '1-5 кг'), ('2', '6-10 кг'), ('3', '11-20 кг'), ('4', '21+ кг')], default='1', max_length=10, verbose_name='Вес'),
        ),
    ]
