# Generated by Django 5.0.6 on 2024-06-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_host_pet_customer_alter_pet_age_months_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='customer',
            new_name='host',
        ),
    ]
