# Generated by Django 5.0.6 on 2024-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_customer_pet_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age_months',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age_years',
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.CharField(choices=[('1', 'до 1 года'), ('2', '1 - 5 лет'), ('3', '5 - 8 лет'), ('4', 'старше 8 лет')], default='1', max_length=10, verbose_name='Возраст'),
        ),
    ]
