# Generated by Django 5.0.6 on 2024-06-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_pet_age_months_remove_pet_age_years_pet_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
