# Generated by Django 5.0.6 on 2024-06-08 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_pet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('собака', 'Собака'), ('кошка', 'Кошка')], default='собака', max_length=6, verbose_name='Тип питомца')),
                ('image', models.ImageField(blank=True, default='images/profile/pet_default.png', null=True, upload_to='images/pets/%Y/%m/%d/', verbose_name='Фото')),
                ('name', models.CharField(max_length=50, verbose_name='Имя питомца')),
                ('breed', models.CharField(blank=True, max_length=50, null=True, verbose_name='Порода')),
                ('age', models.CharField(choices=[('1', 'до 1 года'), ('2', '1 - 5 лет'), ('3', '5 - 8 лет'), ('4', 'старше 8 лет')], default='1', max_length=10, verbose_name='Возраст')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('weight', models.CharField(choices=[('1', '1-5 кг'), ('2', '6-10 кг'), ('3', '11-20 кг'), ('4', '21+ кг')], default='1', max_length=10, verbose_name='Вес')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин')),
            ],
        ),
    ]
