# Generated by Django 5.0.6 on 2024-06-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cat_type',
            field=models.CharField(choices=[('передержка', 'Передержка'), ('выгул', 'Выгул'), ('няня', 'Няня')], default='передержка', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.TextField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('заказчик', 'Я - клиент'), ('исполнитель', 'Я - ситтер')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(choices=[('до 1 года', 'до 1 года'), ('1 - 5 лет', '1 - 5 лет'), ('5 - 8 лет', '5 - 8 лет'), ('старше 8 лет', 'старше 8 лет')], default='до 1 года', max_length=25, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.CharField(choices=[('1-5 кг', '1-5 кг'), ('6-10 кг', '6-10 кг'), ('11-20 кг', '11-20 кг'), ('21+ кг', '21+ кг')], default='1-5 кг', max_length=25, verbose_name='Вес'),
        ),
    ]
