# Generated by Django 5.0.6 on 2024-06-12 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_service_servicecategory_service_cat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='categoryTrough',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='postTrough',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='service',
            name='cat',
            field=models.ManyToManyField(related_name='ServiceCategory', through='core.ServiceCategory', to='core.category', verbose_name='Вид услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
    ]
