# Generated by Django 5.0.6 on 2024-06-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_categorytrough_servicecategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
