# Generated by Django 5.0.6 on 2024-06-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cat',
            new_name='category',
        ),
    ]
