# Generated by Django 5.0.6 on 2024-06-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_cat_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cat_type',
            field=models.CharField(blank=True, choices=[('передержка', 'Передержка'), ('выгул', 'Выгул'), ('няня', 'Няня')], max_length=20, null=True),
        ),
    ]
