# Generated by Django 5.0.6 on 2024-06-16 07:41

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customer_cat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cat_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('передержка', 'Передержка'), ('выгул', 'Выгул'), ('няня', 'Няня')], max_length=100, null=True, verbose_name='Профили работы'),
        ),
    ]
