# Generated by Django 5.0.6 on 2024-06-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_customer_cat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='about_me',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
