# Generated by Django 5.0.6 on 2024-06-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customer_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='about_me',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.TextField(blank=True, max_length=70, null=True, verbose_name='Моя цитата'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery/%Y/%m/%d/', verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
