# Generated by Django 5.0.6 on 2024-06-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_customer_about_me_alter_customer_bio_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
