# Generated by Django 5.0.6 on 2024-06-16 18:01

import core.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coordinates',
            field=core.custom_fields.CoordinateField(blank=True, max_length=50, null=True, verbose_name='Координаты'),
        ),
    ]
