# Generated by Django 5.0.6 on 2024-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_images_image_images_images_alter_images_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/gallery/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
