# Generated by Django 5.0.6 on 2024-06-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customer_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='images',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
