# Generated by Django 5.0.6 on 2024-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_customer_images_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='house_type',
            field=models.CharField(blank=True, choices=[('квартира', 'квартира'), ('частный дом', 'частный дом')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kids',
            field=models.CharField(blank=True, choices=[('есть', 'есть'), ('нет', 'нет')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pet_size',
            field=models.CharField(blank=True, choices=[('любой', 'любой'), ('1-5 кг', '1-5 кг'), ('6-10 кг', '6-10 кг'), ('11-20 кг', '11-20 кг'), ('21+ кг', '21+ кг')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sit_pet',
            field=models.CharField(blank=True, choices=[('кошка', 'кошка'), ('собака', 'собака'), ('отсутствуют', 'отсутствуют')], max_length=20, null=True),
        ),
    ]
