# Generated by Django 5.0.6 on 2024-06-16 19:52

import core.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_customer_exp_customer_house_type_customer_kids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coordinates',
            field=core.custom_fields.CoordinateField(blank=True, max_length=50, null=True, verbose_name='Координаты'),
        ),
    ]
