# Generated by Django 5.0.6 on 2024-06-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_gallery_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='customer',
            new_name='user',
        ),
    ]
