# Generated by Django 5.0.6 on 2024-06-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_customer_gallery_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
