# Generated by Django 5.0.6 on 2024-06-18 06:57

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sit_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cat_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('boarding', 'Передержка'), ('walk', 'Выгул'), ('daycare', 'Няня')], max_length=100, null=True, verbose_name='Профили работы'),
        ),
    ]
