# Generated by Django 5.0.6 on 2024-06-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_customer_sit_type_alter_customer_cat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sit_type',
        ),
    ]
