# Generated by Django 5.0.6 on 2024-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_customer_cat_type_alter_customer_sit_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lowest_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
